<?php
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Session\AccountInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_language_switch_links_alter()
 */
function language_access_language_switch_links_alter(&$links, $type, $path) {
  $user =  \Drupal::currentUser();
  $languages = Drupal::languageManager()->getLanguages();

  foreach ($languages as $language) {
    $id = $language->getId();
    if (!$user->hasPermission('access language ' . $id)) {
      if (isset($links[$id])) unset($links[$id]);
    }
  }
}

/**
 * Implements hook_node_access().
 */
function language_access_node_access(NodeInterface $node, $op, AccountInterface $account) {
  if ($op == 'view') {
    /** @var Drupal\Core\Language\Language $language */
    $language = $node->language();
    if (!$account->hasPermission('access language ' . $language->getId())) {
      return AccessResult::forbidden();
    }
  }

  return AccessResult::neutral();
}
